### PR TITLE
Fix rename on virtual folders

### LINKED ISSUE #207: rename in SAF Mode
When I access ftpd via win7+Filezilla in SAF mode and rename a file (on the sdcard), I always get an ftp log like this:
```
Status:	Directory listing of "/testFS" successful
Status:	Renaming '/testFS/Die Zeit mit.pdf' to '/testFS/Die Zeit mit Magazin.pdf'
Command:	RNFR 20190808-Die Zeit mit.pdf
Response:	350 Requested file action pending further information.
Command:	RNTO 20190808-Die Zeit mit Magazin.pdf
Response:	553 Can't rename file.
```
A second later after that, the rename is done.

I encounter the same phenomen when I use FreeFileSync.
After a sync, it tries to rename its database file:
```
Die Datei 
"ftp://192.168.178.40/testFS/sync.ffs_db.0d1d.ffs_tmp" kann nicht nach 
"ftp://192.168.178.40/testFS/sync.ffs_db" verschoben werden.
CURLE_QUOTE_ERROR: QUOT command failed with 553
553 Can't rename file. [curl_easy_perform]
```

With Filezilla it's easy to live with that, but FFS aborts with an error.
Is it that Android says "ok, done" but some kind of writing cache takes time or a reading cache hasn't updated yet?
What's up here? Thank you!

### PR DESCRIPTION
**Pull request by lmagyar**
fixes #207

Note: This is my first ever Java code, tested on real Phone (Samsung A8, Android 9.0, connecting with WinSCP), because rename doesn't work on the emulator, I mean even the plain SAF without virtual folders failed with rename, but it works on a real phone with real SD card (plain SAF and virtual folders also).

### CODE REVIEW

**Comment by lmagyar** [comment]
The fix for the FTP virtual file is not tested, though it builds, and the issue/fix is totally equivalent with the SSH version.

File: primitiveFTPd/src/org/primftpd/filesystem/VirtualFtpFile.java [hunk 1]
```diff
@@ -44,7 +44,7 @@ public String getClientIp() {
     @Override
     public boolean move(FtpFile target) {
         logger.trace("move()");
-        return delegate != null && ((FtpFile) delegate).move(target);
+        return delegate != null && ((FtpFile) delegate).move((FtpFile) ((VirtualFtpFile) target).delegate);
```
Comment (wolpi) [inline primitiveFTPd/src/org/primftpd/filesystem/VirtualFtpFile.java:47]: Cast to FtpFile should be removed and only be casted to VirtualFtpFile

File: primitiveFTPd/src/org/primftpd/filesystem/VirtualSshFile.java [hunk 2]
```diff
@@ -43,7 +43,7 @@ public String getClientIp() {
     @Override
     public boolean move(SshFile target) {
         logger.trace("move()");
-        return delegate != null && ((SshFile) delegate).move(target);
+        return delegate != null && ((SshFile) delegate).move((SshFile) ((VirtualSshFile) target).delegate);
```
Comment (wolpi) [inline primitiveFTPd/src/org/primftpd/filesystem/VirtualSshFile.java:46]: Same as above

**Comment by wolpi** [comment]
good catch that casting is necessary here :)

File: primitiveFTPd/src/org/primftpd/filesystem/VirtualFtpFile.java (hunk 1 above)
Comment (lmagyar) [reply primitiveFTPd/src/org/primftpd/filesystem/VirtualFtpFile.java:47]: The FtpFile cast is for the delegate! ;) The delegate is AbstractFile, we have to cast it to something, and we call FtpFile's move(), and that uses FtpFile as argument. So I think this is correct as is.

Comment (wolpi) [reply primitiveFTPd/src/org/primftpd/filesystem/VirtualFtpFile.java:47]: Ah, now I see. The important piece is to pass target.delegate. Therefore all the casts are necessary.
